config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/",
         include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(),  name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"
urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add",
         views.AddPhotoView.as_view(),
         name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/",
         views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/",
         views.EditPhotoView.as_view(), name="edit-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path(
        "login/github/callback/",
        views.github_callback,
        name="github-callback"
    ),
    path(
        "login/kakao/callback/",
        views.kakao_callback,
        name="kakao-callback"
    ),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification,
         name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfile.as_view(), name="update"),
    path("update-password/", views.UpdatePassword.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_lang, name="switch-language"),
    path("conversations/", views.conversations, name="conversation"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-400">
    <div class="flex flex-col">
    &copy; BSaFe, Inc. <br>All rights reserved. <br><br><br> email : cbr5964@sogang.ac.kr <br> homepage : https://github.com/b-chae
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
<div class="absolute top-5 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <div class="mymessage z-10 font-medium rounded-full text-white py-4 px-6 w-2/3 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{message}}</div>
    {% endfor %}
</div>
{% endif %}

templates/partials/nav.html
    <ul class="flex items-center text-sm font-medium h-full">
        <li class="nav_link">
            <a class="flex justify-between items-center" href='{% url "rooms:search" %}'>
            <i class="fas fa-globe-americas mr-2 text-indigo-900"></i>
            <span class="text-indigo-800 font-bold">Explore</span>
            </a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav_link">
                <a href='{% url "users:switch-hosting" %}'>
                {% if request.session.is_hosting %}
                    Stop hosting
                {% else %}
                    Start hosting
                {% endif %}   
                </a>
            </li>
            {% if request.session.is_hosting %}
            <li class="nav_link"><a href='{% url "rooms:create" %}'>Create Room</a></li>
            {% endif %}
            <li class="nav_link"><a href='{% url "users:profile" user.pk%}'>Profile</a></li>
            {% if not request.session.is_hosting and user.lists.rooms.count > 0 %}
                <li class="nav_link"><a href='{% url "lists:see-favs" %}'>Favs ({{user.lists.rooms.count}})</a></li>
            {% endif %}
            <li class="nav_link"><a href='{% url "users:logout" %}'>Log out</a></li>
        {% else %}
        <li class="nav_link"><a href='{% url "users:login" %}'>Log in</a></li>
        <li class="nav_link"><a href='{% url "users:signup" %}'>Sign up</a></li>
        {% endif %}
    </ul>

templates/partials/social_login.html
<div class="btn flex flex-col w-full">
    <div class="text-center w-full mx-auto">🚧 아직 소셜 로그인이 원활하지 않습니다</div>
    <div class="text-center w-full mx-auto mb-3">😅 이메일로 가입을 권장합니다</div>
    <a href="{% url 'users:github-login' %}" class="btn border-2 border-gray-700 text-grey-700 mb-2 bg-white">
        <i class="fab fa-github mr-2 fa-lg"></i>Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn border-2 border-yellow-500 text-yellow-700 mb-2 bg-yellow-300">
        <i class="fas fa-comment mr-2 fa-lg"></i>Continue with Kakao
    </a>
</div>

<div class="flex items-center w-full">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-700 font-medium mx-4">
        or
    </span>
    <div class="h-px w-full bg-gray-500"></div>
</div>