config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/",
         include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(),  name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"
urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("confirm/<int:room>/<int:year>-<int:month>-<int:day>/",
         views.confirm, name="confirm"),
    path("create/<int:room>/<int:year>-<int:month>-<int:day>/",
         views.create, name="create"),
    path("<int:pk>/", views.ReservationDetail.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("lists/", views.reservations_list, name="lists"),
    path("<int:pk>/delete/", views.reservation_delete, name="delete"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add",
         views.AddPhotoView.as_view(),
         name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/",
         views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/",
         views.EditPhotoView.as_view(), name="edit-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path(
        "login/github/callback/",
        views.github_callback,
        name="github-callback"
    ),
    path(
        "login/kakao/callback/",
        views.kakao_callback,
        name="kakao-callback"
    ),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification,
         name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfile.as_view(), name="update"),
    path("update-password/", views.UpdatePassword.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_lang, name="switch-language"),
    path("conversations/", views.conversations, name="conversation"),
]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    price = forms.IntegerField(required=False, min_value=0)
    room_type = forms.ModelChoiceField(
        empty_label="Any kind",
        queryset=models.RoomType.objects.all(),
        required=False
    )
    price = forms.IntegerField(required=False, min_value=0, widget=forms.NumberInput(
        attrs={'placeholder': 'Maximum Price'}))
    guests = forms.IntegerField(required=False, min_value=0,
                                max_value=10, widget=forms.NumberInput(attrs={'class': 'h-10'}))
    bedrooms = forms.IntegerField(
        required=False, min_value=0, max_value=10, widget=forms.NumberInput(attrs={'class': 'h-10'}))
    beds = forms.IntegerField(required=False, min_value=0, max_value=10,
                              widget=forms.NumberInput(attrs={'class': 'h-10'}))
    baths = forms.IntegerField(required=False, min_value=0, max_value=10,
                               widget=forms.NumberInput(attrs={'class': 'h-10'}))
    instant_book = forms.BooleanField(
        required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'h-48'}),
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'h-48'}),
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, user, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from .import models, forms

# Limiting Querysets
# all_rooms = models.Room.objects.all()[:5]
# just pointing the DB, not loading

# url에서 오는 모든 것은 Get Request 이다 !
# print(request.GET)
# http://127.0.0.1:8000/?page=1&city=seoul


class HomeView(ListView):
    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 3
    ordering = "-created"
    page_kwarg = "page"


class RoomDetail(DetailView):

    """ Room Detail Definition """

    model = models.Room
    pk_url_kwarg = "pk"


class SearchView(View):

    def get(self, request):
        country = request.GET.get("country", None)
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                price = form.cleaned_data.get("price")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}
                if city != "Anywhere":
                    filter_args["city__startswith"] = city
                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(
                    **filter_args).order_by("-created")
                paginator = Paginator(qs, 12, orphans=3)
                page = int(request.GET.get("page", 1))
                rooms = paginator.get_page(page)

                getstr = ""
                for i in form.data:
                    if i != "page":
                        getstr += '&' + i + '=' + form.data.get(i)
                return render(request,
                              "rooms/search.html",
                              {
                                  "form": form,
                                  "rooms": rooms,
                                  "page_obj": paginator.page(page),
                                  "getstr": getstr,
                              }
                              )
        else:
            form = forms.SearchForm()
            qs = models.Room.objects.all().order_by("-created")
            paginator = Paginator(qs, 12, orphans=3)
            page = int(request.GET.get("page", 1))
            rooms = paginator.get_page(page)

        return render(request, "rooms/search.html", {"form": form, "rooms": rooms,
                                                     "page_obj": paginator.page(page), })


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):

    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Page not Found")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted!")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))

    return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))


class EditPhotoView(user_mixins.LoggedInOnlyView,
                    SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption", )
    success_message = "Photo Updated"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})

    def get_object(self, queryset=None):
        photo = super().get_object(queryset=queryset)
        if photo.room.host.pk != self.request.user.pk:
            raise Http404()
        return photo


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/photo_create.html"
    fields = ("file", "caption",)
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        room = models.Room.objects.get(pk=pk)
        if room.host.pk != self.request.user.pk:
            messages.error(self.request, "You can't edit photo")
            return redirect(reverse("core:home"))
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={'pk': pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):
    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save(self.request.user)
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Uploaded")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/photo_create.html
{% extends 'base.html' %}


{% block page_title %}
    Upload Photo
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-2/3 xl:w-1/2 mx-auto my-10 p-5 flex flex-col items-center border">
        {% include 'mixins/rooms/room_form.html' with form=form cta="Upload photo" %}
    </div>
{% endblock content %}
    

templates/rooms/photo_edit.html
{% extends 'base.html' %}


{% block page_title %}
    Update Photo
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-2/3 xl:w-1/2 mx-auto my-10 p-5 flex flex-col items-center border">
        {% include 'mixins/rooms/room_form.html' with form=form cta="Update photo" %}
    </div>
{% endblock content %}
    

templates/rooms/room_create.html
{% extends 'base.html' %}


{% block page_title %}
    Create Room
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-2/3 xl:w-1/2 mx-auto my-10 p-5 flex flex-col items-center border">
        {% include 'mixins/rooms/room_form.html' with form=form cta="Create room" %}

    </div>
{% endblock content %}
    

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load is_booked on_favs i18n %}

{% block page_title %}
{{room.name}}
{% endblock page_title %}

{% block content %}
<div class="-mt-5">
    <div class="container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-center bg-cover shadow-lg m-1px hover:opacity-80 hover:w-1/3" style="background-image: url({{room.first_photo}});"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div class="w-1/2 h-auto bg-cover bg-center shadow-lg m-1px hover:opacity-80" style="background-image: url({{photo.file.url}});"></div>
            {% endfor %}
        </div>
</div>

<div class="container mx-auto flex justify-around pb-56">
    <div class="w-1/2">
        <div class="flex justify-between">
            <div>
                <span class="text-3xl font-medium mb-px mr-3">
                    {{room.name}}
                </span> <br>
                <span class="text-gray-400 font-light">
                    {{room.city}}
                </span>
            </div>
            <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=room.host%}
                <span class="mt-1 text-light text-gray-500 text-xs">
                    {{room.host.first_name}}
                </span>
            </a>
        </div>
        <div class="flex border-section">
            <span class="mr-5 font-light">{{room.room_type}}</span>
            <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
            <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
            <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
            <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
        </div>
        <p class="flex border-section">
            {{room.description}}
        </p>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">
                Amenities
            </h4>
            <ul>
            {% for amenity in room.amenities.all %}
                <li class="mb-2">{{amenity}}</li>
            {% endfor %}
            </ul>
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">
                Facilities
            </h4>
            <ul>
            {% for f in room.facilities.all %}
                <li class="mb-2">{{f}}</li>
            {% endfor %}
            </ul>
        </div>
        <div class="border-section">
            <h4 class="font-medium text-lg mb-5">
                House rules
            </h4>
            
            <ul>
            {% for h in room.house_rules.all %}
                <li class="mb-2">{{h}}</li>
            {% endfor %}
            </ul>
        </div>
        <div class="flex flex-col">
            <h4 class="font-bold text-2xl mb-5 mt-5">
                Reviews
            </h4>
            
            <div class="flex items-center">
                <div>
                    <i class="fas fa-star text-green-600"></i>
                    <span class="font-bold text-xl mr-5">{{room.total_rating}}</span>
                </div>
                <div class="h-5 w-px bg-gray-400 mr-5"></div>
                <span class="font-bold text-xl mr-3">{{room.reviews.count}}</span>
                <span>review{{room.reviews.count | pluralize}}</span>
            </div>

            
            {% if room.reviews.count > 0 %}
            
            <div class="flex items-center flex-col w-full">
                <div class="w-full m-3 flex felx-row">
                    <span class="font-bold text-gray-800 w-2/3">Accuracy</span>
                    <span class="font-bold ml-3 mr-3 w-1/3">{{room.total_accuracy}}</span>
                    <div class="w-full">
                        {% with ''|center:room.total_accuracy as range %}
                        {% for _ in range %}
                        <i class="fas fa-star text-green-600"></i>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                
                <div class='w-full h-px bg-gray-400'></div>
                
                <div class="w-full m-3 flex felx-row">
                    <span class="font-bold text-gray-800 w-2/3">Communication</span>
                    <span class="font-bold ml-3 mr-3 w-1/3">{{room.total_communication}}</span>
                    <div class="w-full">
                        {% with ''|center:room.total_communication as range %}
                        {% for _ in range %}
                        <i class="fas fa-star text-green-600"></i>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                
                <div class='w-full h-px bg-gray-400'></div>
                
                <div class="w-full m-3 flex felx-row">
                    <span class="font-bold text-gray-800 w-2/3">Cleanliness</span>
                    <span class="font-bold ml-3 mr-3 w-1/3">{{room.total_cleanliness}}</span>
                    <div class="w-full">
                        {% with ''|center:room.total_cleanliness as range %}
                        {% for _ in range %}
                        <i class="fas fa-star text-green-600"></i>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                
                <div class='w-full h-px bg-gray-400'></div>
                
                <div class="w-full m-3 flex felx-row">
                    <span class="font-bold text-gray-800 w-2/3">Location</span>
                    <span class="font-bold ml-3 mr-3 w-1/3">{{room.total_location}}</span>
                    <div class="w-full">
                        {% with ''|center:room.total_location as range %}
                        {% for _ in range %}
                        <i class="fas fa-star text-green-600"></i>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                
                <div class='w-full h-px bg-gray-400'></div>
                
                <div class="w-full m-3 flex felx-row">
                    <span class="font-bold text-gray-800 w-2/3">Check In</span>
                    <span class="font-bold ml-3 mr-3 w-1/3">{{room.total_check_in}}</span>
                    <div class="w-full">
                        {% with ''|center:room.total_check_in as range %}
                        {% for _ in range %}
                        <i class="fas fa-star text-green-600"></i>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                
                <div class='w-full h-px bg-gray-400'></div>
                
                <div class="w-full m-3 flex felx-row">
                    <span class="font-bold text-gray-800 w-2/3">Value</span>
                    <span class="font-bold ml-3 mr-3 w-1/3">{{room.total_value}}</span>
                    <div class="w-full">
                        {% with ''|center:room.total_value as range %}
                        {% for _ in range %}
                        <i class="fas fa-star text-green-600"></i>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                
            </div>
            {% endif %}
            
            <div class="mt-10">
                {% for review in room.reviews.all %}
                <div class="border-section">
                    <div class="flex mb-3">
                        <a href="{% url 'users:profile' review.user.pk %}">
                            {% include 'mixins/user_avatar.html' with user=review.user h_and_w='w-12 h-12' text='text-2xl'%}
                        </a>
                        <div class="flex flex-col ml-5">
                        <span class="font-medium">{{review.user.first_name}}</span>
                        <span class="text-sm text-gray-500">
                            {{review.created|date:'F Y'}}
                        </span>
                        </div>
                    </div>
                    <p>{{review.review}}</p>
                    </div>
                {% endfor %}
                    
            </div>
        </div>

    </div>
    <div class="w-1/3">
        {% if room.host == user %}
    <a href="{% url 'rooms:edit' room.pk%}" class="btn_link block">Edit Room</a>
        {% else %}
            {% if not request.session.is_hosting %}
            {% if user.is_authenticated %}
                {% on_favs room as on_favs_boolean %}
                {% if on_favs_boolean %}
                    <a href="{% url 'lists:toggle-room' room.pk %}" class="btn bg-green-400 text-white rounded-lg block mb-5">Save to Favorites</a>
                {% else %}
                    <a href="{% url 'lists:toggle-room' room.pk %}" class="btn bg-red-400 text-white rounded-lg block mb-5">Remove from Favorites</a>
                {% endif %}
            {% endif %}
                {% for calendar in room.get_calendars %}
                <div class="mb-20">
                    <span class="text-center font-medium text-lg block mb-8">{{calendar.get_month}}/{{calendar.year}}</span>
                    <div class="cal-grid mb-4 font-semibold">
                        {% for day in calendar.day_names %}
                            <span>{{day}}</span>
                        {% endfor %}
                    </div>
                    <div class="cal-grid">
                        {% for day in calendar.get_days %}
                            {% is_booked room day as is_booked_bool %}
                            {% if day.day != 0 %}
                                {% if day.past %}
                                    <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300">
                                        {{day}}
                                    </span>
                                {% elif is_booked_bool %}
                                    <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-600 line-through">
                                        {{day}}
                                    </span>
                                {% else %}
                                    <a href='{% url "reservations:confirm" room.pk day.year day.month day.day %}'class="bg-gray-200 w-full text-center rounded text-gray-700 p-1 hover:bg-green-600 hover:text-white cursor-pointer font-medium">{{day}}</a>
                                {% endif %}
                            {% else %}
                                <span></span>
                            {% endif %} 
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}


{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}
    <div class="container my-10 mx-auto flex flex-col">

        <a href="{% url "rooms:add-photo" room.pk %}" class="btn_link m-10 w-1/3">Upload Photo</a>
        
        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32"/>
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn bg-indigo-400 mb-5 text-white rounded-lg block" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="btn bg-red-500 mb-5 text-white rounded-lg block" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center">
            <a href="{{room.get_absolute_url}}/edit" class="text-blue-500 font-medium text-xl">
                Back to edit room</a>
        </div>

    </div>
{% endblock content %}
    

templates/rooms/search.html
{% extends 'base.html' %}


{% block page_title %}

Search
    
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="items-center flex-col mx-auto w-full text-center">
    <form method="get" action="{% url "rooms:search" %}">
        <div class="flex flex-col lg:w-2/3 md:w-3/4 sm:w-full mx-auto shadow pb-5 px-5 items-center justify-center">
            <div class="flex flex-wrap m-1 mt-5 justify-center items-center">
                <div class="mr-3">{{form.city}}</div>
                <div class="mr-3">{{form.country}}</div>
            </div>
            <div class="flex flex-wrap m-1 justify-center">
                <div class="mr-3">{{form.room_type}}</div>
                <div class="mr-3">{{form.price}}</div>
                <div class="flex flex-row items-center ml-12 justify-center">
                {% for field in form %}
                    {% if field.name == 'superhost' or field.name == 'instant_book' %}
                        <div class="mr-2 flex flex-row items-center w-32 h-auto">
                            <div class="w-auto h-auto font-medium">{{field.label_tag}}</div>
                            <div class="w-full h-auto">{{field}}</div>
                        </div>
                    {% endif %}
                {% endfor %}
                </div>
            </div>
            <div class="flex flex-wrap m-1 justify-center">
                <div class="mr-3">{{form.amenities}}</div>
                <div class="mr-3">{{form.facilities}}</div>
            </div>
            <div class="flex flex-wrap m-1 items-center text-center font-medium justify-center">
                <div class="flex flex-row items-center text-center justify-center">
                    <div class="mr-3">{{form.guests.label_tag}}</div>
                    <div class="mr-3">{{form.guests}}</div>
                </div>
                <div class="flex flex-row items-center text-center justify-center">
                    <div class="mr-3">{{form.bedrooms.label_tag}}</div>
                    <div class="mr-3">{{form.bedrooms}}</div>
                </div>
                <div class="flex flex-row items-center text-center justify-center">
                    <div class="mr-3">{{form.beds.label_tag}}</div>
                    <div class="mr-3">{{form.beds}}</div>
                </div>
                <div class="flex flex-row items-center text-center justify-center">
                    <div class="mr-3">{{form.baths.label_tag}}</div>
                    <div class="mr-3">{{form.baths}}</div>
                </div>
            </div>
                <button class="btn_link">Search</button>
        </div>
    </form>
</div>
    

<div class="container lg:w-3/4 md:w-10/12 sm:w-full h-full mx-auto my-10 mb-48 flex flex-col items-center">
    <div class="mb-12 text-2xl font-medium">
        Results
    </div>
    <div class="flex flex-wrap -mx-40 mb-10 w-full h-auto justify-center">
        {% for room in rooms %}
            {% include 'mixins/rooms/room_card.html' with room=room %}
        {% endfor %}
    </div>

    <div class="text-gray-800 font-medium flex flex-row items-center">
    {% if page_obj.has_previous %}
    <a class="hover:bg-green-300 p-2 mx-5 text-white bg-green-500 rounded-full" href="?page={{page_obj.previous_page_number}}{{getstr}}">Previous</a>
    {% endif %}
        {{page_obj.number}} / {{page_obj.paginator.num_pages}}
    {% if page_obj.has_next %}
    <a class="hover:bg-green-300 p-2 mx-5 text-white bg-green-500 rounded-full" href="?page={{page_obj.next_page_number}}{{getstr}}">Next</a>
    {% endif %} </div>
</div>  
    
{% endblock content %}
    