config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/",
         include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(),  name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"
urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("confirm/<int:room>/<int:year>-<int:month>-<int:day>/",
         views.confirm, name="confirm"),
    path("create/<int:room>/<int:year>-<int:month>-<int:day>/",
         views.create, name="create"),
    path("<int:pk>/", views.ReservationDetail.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("lists/", views.reservations_list, name="lists"),
    path("<int:pk>/delete/", views.reservation_delete, name="delete"),
]

lists/models.py
from django.db import models
from core import models as core_models


class List(core_models.TimeStampedModel):

    name = models.CharField(max_length=80)
    user = models.OneToOneField(
        "users.User", related_name="lists", on_delete=models.CASCADE)
    rooms = models.ManyToManyField(
        "rooms.Room", related_name="lists", blank=True)

    def __str__(self):
        return self.name

    def count_rooms(self):
        return self.rooms.count()

    count_rooms.short_description = "Number of Rooms"

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):
    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING)
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE)
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE)

    check_in = models.DateField()
    check_out = models.DateField()
    purpose = models.CharField(max_length=80, blank=True, null=True)

    def __str__(self):
        return f'{self.room} - {self.check_in} ~ {self.check_out}'

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end), reservation=self).exists()
            if not existing_booked_day:
                r = super().save(*args, **kwargs)
                for i in range(difference.days):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return r
        else:
            return super().save(*args, **kwargs)

lists/views.py
from django.contrib import messages
from django.views.generic import TemplateView
from django.shortcuts import redirect, reverse
from rooms import models as room_models
from . import models


def toggle_room(request, room_pk):
    room = room_models.Room.objects.get(pk=room_pk)
    if room is not None:
        the_list, _ = models.List.objects.get_or_create(
            user=request.user, name="My Favorite Houses")
        if room in the_list.rooms.all():
            the_list.rooms.remove(room)
            messages.success(request, "Removed from my favorite list")
        else:
            if the_list.rooms.count() < 20:
                the_list.rooms.add(room)
                messages.success(request, "Added to my favorite list")
            else:
                messages.error(request, "Too many rooms in your favorite list")
    else:
        messages.error(request, "Page Not Found")
        return redirect(reverse("core:home"))
    return redirect(reverse("rooms:detail", kwargs={"pk": room_pk}))


class SeeFavsView(TemplateView):
    template_name = "lists/list_detail.html"

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.db.models import Q
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


def confirm(request, room, year, month, day):

    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))

    try:
        date_obj = datetime.datetime(year=year, month=month, day=day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't reserve that room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        return render(request,
                      "reservations/confirm.html",
                      {"room": room,
                       "year": year,
                       "month": month,
                       "day": day})


def reservation_delete(request, pk):

    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))

    reservation = models.Reservation.objects.get(pk=pk)
    if request.user != reservation.room.host:
        raise Http404()

    reservation.delete()
    return redirect(reverse("reservations:lists"))


def create(request, room, year, month, day):

    if not request.user.is_authenticated:
        return redirect(reverse("users:login"))

    try:
        date_obj = datetime.datetime(year=year, month=month, day=day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't reserve that room")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),

        )
        return redirect(reverse("reservations:detail",
                                kwargs={"pk": reservation.pk}))


class ReservationDetail(View):
    def get(self, *args, **kwargs):
        reservation = models.Reservation.objects.get_or_none(pk=kwargs['pk'])
        if not reservation:
            raise Http404()
        elif (reservation.guest != self.request.user
              and reservation.room.host != self.request.user):
            raise Http404()
        form = review_forms.CreateReviewForm()
        return render(
            self.request,
            "reservations/detail.html",
            {"reservation": reservation,
             "form": form,
             })


def edit_reservation(request, pk, verb):

    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation:
        raise Http404()
    if not reservation or (
        reservation.guest != request.user
        and reservation.room.host != request.user
    ):
        raise Http404()

    if verb == "confirm":
        if reservation.room.host != request.user:
            raise Http404()
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation updates!")
    return render(
        request,
        "reservations/detail.html",
        {"reservation": reservation})


def reservations_list(request):
    reservations = models.Reservation.objects.filter(
        Q(guest=request.user) | Q(room__host=request.user))

    return render(request, "reservations/lists.html", {"reservations": reservations})

templates/reservations/confirm.html
{% extends 'base.html' %}


{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}
    <div class="container my-10 mx-auto flex flex-col">

        <div class="border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{room.first_photo}});">
        </div>
        
        <div class="flex flex-col items-start border-l border-r border-t border-b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{year}}/{{month}}/{{day}}
            </div>
    
            <span class="text-xl border-b mt-2 p-5 w-full">
                {{room.name}}
            </span>
    
            <div class="w-full">
                <div class="flex my-10 p-5 border-b w-full">
                    <div class="flex flex-col items-center">
                        <a href="{{room.host.get_absolute_url}}">
                        {% include 'mixins/user_avatar.html' with user=room.host %}</a>
                        <span class="text-gray-400 mt-2">{{room.host.first_name}}</span>
                    </div>
                </div>
            </div>
    
            <div class="pb-5 px-5 flex flex-col justify-center w-full mx-auto">
                <span class="font-medium text-2xl text-center w-full block mb-5">Are you sure to make a new reservation?</span>
                <a class="btn_link mt-2 rounded-lg w-1/3 mx-auto" href="{% url 'reservations:create' room.pk year month day %}">Yes</a>
                <a class="btn_link mt-2 rounded-lg w-1/3 mx-auto" href="{% url 'rooms:detail' room.pk %}">Back to Previous Page</a>
            </div>
        </div>

    </div>
{% endblock content %}
    

templates/reservations/detail.html
{% extends 'base.html' %}


{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}
    <div class="container my-10 mx-auto flex flex-col">

        <div class="border-t border-l border-r bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});">
        </div>
        
        <div class="flex flex-col items-start border-l border-r border-t border-b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{reservation.check_in}} - {{reservation.check_out}}
                <span class=' ml-5 {% if reservation.status == "pending" %} text-yellow-500 {% elif reservation.status == "canceled" %} text-red-600 {% else %} text-green-600 {% endif %}'>{{reservation.get_status_display}}</span>
            </div>
    
            <span class="text-xl border-b mt-2 p-5 w-full">
                {{reservation.room.name}}
            </span>
    
            <div class="w-full">
                <div class="flex my-10 p-5 border-b w-full">
                    <div class="flex flex-col items-center">
                        <a href="{{reservation.room.host.get_absolute_url}}">
                        {% include 'mixins/user_avatar.html' with user=reservation.room.host %}</a>
                        <span class="text-gray-400 mt-2">{{reservation.room.host.first_name}}</span>
                    </div>
                    <div class="ml-5 flex flex-col">
                        <span class="font-medium mb-px">Contact your Airbnb Host</span>
                        <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="font-medium text-blue-500 py-2">Send a Message</a>
                    </div>
                </div>
            </div>
    
            <div class="pb-5 px-5 flex flex-col">
            {% if reservation.status != 'canceled' %}
                {% if reservation.status == 'confirmed' and reservation.is_finished and reservation.room.host != user%}
                <span class="font-medium text-2xl text-center w-full block mb-5">Write your review</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-2/3 mx-auto">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn_link mt-10 rounded-lg">Submit Review</button>
                    </form>
                {% else %}
                        {% if reservation.status == 'pending' %}
                            {% if reservation.room.host == user %}
                                <a href = "{% url 'reservations:edit' reservation.pk 'confirm' %}"class="btn_link rounded-lg block px-5 mb-5">Confirm Reservation</a>
                            {% endif %}
                        <a href = "{% url 'reservations:edit' reservation.pk 'cancel' %}"class="btn_link  rounded-lg block px-5 mb-5">Cancel Reservation</a>
                        {% endif %}
                    {% endif %}  
                {% endif %}
            </div>
        </div>

    </div>
{% endblock content %}
    

templates/reservations/lists.html
{% extends 'base.html' %}


{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}

<div class='w-full m-10 flex flex-col justify-center text-center'>
    <div class="font-medium text-lg mb-10">
        My Reservation Lists
    </div>
        
    {% for r in reservations %}
        <div class="mb-3 w-full border-b">
            <a class="{% if r.guest.pk == user.pk %} text-gray-900 {% else %} text-pink-500 {% endif %} hover:underline hover:text-gray-400" href='{% url "reservations:detail" r.pk %}'> ({{r.status}}) {{r.room.name}} / {{r.check_in}} </a>
            {% if r.status == 'canceled' and r.room.host == user%}
                <a href="{% url 'reservations:delete' r.pk %}" class="ml-10">❎</a>
            {% endif %}
        </div>
    {% endfor %}
</div>
    
{% endblock content%}