config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/",
         include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/",
         include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(),  name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"
urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path(
        "login/github/callback/",
        views.github_callback,
        name="github-callback"
    ),
    path(
        "login/kakao/callback/",
        views.kakao_callback,
        name="kakao-callback"
    ),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification,
         name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfile.as_view(), name="update"),
    path("update-password/", views.UpdatePassword.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_lang, name="switch-language"),
    path("conversations/", views.conversations, name="conversation"),
]

conversations/forms.py
from django import forms


class AddCommentForm(forms.Form):

    message = forms.CharField(required=True, widget=forms.TextInput(
        attrs={"placeholder": "Add a comment"}))

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    None, forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error(None, forms.ValidationError(
                "User does not exist"))


class SignUpForm(forms.ModelForm):

    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            'first_name': forms.TextInput(attrs={"placeholder": "First name"}),
            'last_name': forms.TextInput(attrs={"placeholder": "Last name"}),
            'email': forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"placeholder": "Password"}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirm your Password"}))

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            self.add_error(None, forms.ValidationError(
                "That email is already taken"))
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            self.add_error(None, forms.ValidationError(
                "Password confirmation does not match"))
        else:
            return password

    def save(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = super().save(commit=False)
        user.username = email
        user.set_password(password)
        user.save()

conversations/views.py
from django.utils import timezone
from django.http import Http404
from django.shortcuts import redirect, reverse, render
from django.views.generic import View
from users import models as user_models
from . import models, forms


def go_conversation(request, a_pk, b_pk):
    user_one = user_models.User.objects.get(pk=a_pk)
    user_two = user_models.User.objects.get(pk=b_pk)
    if user_one is not None and user_two is not None:
        try:
            conversation = models.Conversation.objects.filter(
                participants=user_one).filter(participants=user_two)[0]
        except Exception:
            conversation = models.Conversation.objects.create()
            conversation.participants.add(user_one, user_two)

        return redirect(
            reverse("conversations:detail",
                    kwargs={"pk": conversation.pk}))


class ConversationDetailView(View):

    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        conversation = models.Conversation.objects.get_or_none(pk=pk)
        if not conversation:
            raise Http404()

        if not self.request.user.is_authenticated:
            return render(redirect("users:login"))

        if self.request.user not in conversation.participants.all():
            raise Http404()

        form = forms.AddCommentForm
        return render(self.request, "conversations/conversation_detail.html",
                      {"conversation": conversation,
                       "form": form})

    def post(self, *args, **kwargs):
        message = self.request.POST.get('message')
        pk = kwargs.get("pk")
        conversation = models.Conversation.objects.get_or_none(pk=pk)
        if message is not None:
            models.Message.objects.create(
                message=message,
                user=self.request.user,
                conversation=conversation,
            )
        conversation.save()
        return redirect(reverse("conversations:detail", kwargs={"pk": pk}))

users/views.py
import os
import requests
from django.conf import settings
from django.utils import translation
from django.http import HttpResponse
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, reverse, render
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(
                self.request, f"Welcome back {user.first_name}")
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.info(request, f"See you later {request.user.first_name}")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(
                self.request, f"Welcome back {user.first_name}")
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do : add success message
    except models.User.DoesNotExist:
        # to do : add error message
        pass

    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    print(client_id)
    redirect_url = "http://airbnb-clone.eba-2kktntyc.ap-northeast-2.elasticbeanstalk.com/users/login/github/callback"
    return redirect(
        "https://github.com/login/oauth/authorize"
        + f"?client_id={client_id}"
        + f"&redirect_url={redirect_url}"
        + "&scope=read:user")


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            result = requests.post(
                "https://github.com/login/oauth/access_token"
                + f"?client_id={client_id}"
                + f"&client_secret={client_secret}"
                + f"&code={code}",
                headers={"Accept": "application/json"},
            )
            result_json = result.json()
            error = result_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get access token")
            else:
                access_token = result_json.get("access_token")
                api_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )

                profile_json = api_request.json()
                username = profile_json.get('login', None)
                if username is not None:
                    name = profile_json.get('name')
                    bio = profile_json.get('bio')
                    email = profile_json.get('email')
                    if bio is None:
                        bio = ""
                    if name is None:
                        name = "No Name"
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"You already have an account with {user.login_method}")
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(
                        request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get authorization code")

    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("core:home"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://airbnb-clone.eba-2kktntyc.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
    return redirect(
        "https://kauth.kakao.com/oauth/authorize"
        + f"?client_id={client_id}"
        + f"&redirect_uri={redirect_uri}"
        + "&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://airbnb-clone.eba-2kktntyc.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
        token_request = requests.get(
            "https://kauth.kakao.com/oauth/token?grant_type=authorization_code"
            + f"&client_id={client_id}"
            + f"&redirect_uri={redirect_uri}"
            + f"&code={code}"
        )

        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code")
        access_token = token_json.get("access_token")

        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={
                'Authorization': f'Bearer {access_token}'
            },
        )
        profile_json = profile_request.json()

        try:
            email = profile_json.get("kakao_account").get("email", None)
            if email is None:
                raise KakaoException("Please also give me your email")
        except:
            raise KakaoException("Not allowed. Use email to login")

        nickname = profile_json.get("properties").get("nickname")
        profile_image = profile_json.get("properties").get("profile_image")

        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException(
                    f"You already have an account with {user.login_method}")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()

            if profile_image is not None:
                photo_request = requests.get(profile_image)
                user.avatar.save(f"{nickname}-avatar",
                                 ContentFile(photo_request.content))

        login(request, user)
        messages.success(
            request, f"Welcome back {user.first_name}")
        return redirect(reverse("core:home"))

    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UpdateProfile(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = ("first_name", "last_name", "gender",
              "bio", "birthdate", "language", "currency")
    success_message = "Profile successfully updated!"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['first_name'].widget.attrs = {
            "placeholder": "First Name"
        }
        form.fields['last_name'].widget.attrs = {
            "placeholder": "Last Name"
        }
        form.fields['bio'].widget.attrs = {
            "placeholder": "Bio"
        }
        form.fields['birthdate'].widget.attrs = {
            "placeholder": "Birthdate(****-**-**)"
        }
        return form


class UpdatePassword(
        mixins.LoggedInOnlyView, mixins.EmailLoginOnlyView,
        SuccessMessageMixin, PasswordChangeView):

templates/users/conversations.html
{% extends 'base.html' %}


{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}


{% block search-bar %}  
{% endblock search-bar %}


{% block content %}

<div class='lg:w-1/2 md:w-2/3 sm:w-full m-10 flex flex-col mx-auto justify-center text-center shadow'>
    <div class="font-medium text-2xl my-10 p-5 w-1/2 mx-auto rounded-full bg-blue-400 text-white">
        My Conversations
    </div>
        
    {% for conversation in conversations.all %}
        <div class="m-3 w-auto shadow flex flex-col items-center text-center">
            <div class="flex-row flex justify-left w-full mx-auto items-center">
                {% for parti in conversation.participants.all %}
                <a href="{% url 'users:profile' parti.pk %}" class="m-1">
                    {% include 'mixins/user_avatar.html' with user=parti h_and_w='h-12 w-12' %}
                </a>
                {% endfor %}
                {% for parti in conversation.participants.all %}
                <div class="font-medium text-gray-600">
                    <span class="mr-3">{{parti.first_name}}</span>
                </div>
                {% endfor %}
            <div class="font-light text-xs text-gray-400">
                <span>{{conversation.updated}}</span>
            </div>
            </div>
            <a class="p-5 mx-5 bg-gray-200 hover:bg-gray-500 w-full text-gray-800 font-medium text-left text-lg" href='{% url "conversations:detail" conversation.pk %}'> 
                {{conversation.recent_message}}
            </a>
        </div>
    {% endfor %}
</div>
    
{% endblock content%}

templates/users/login.html
{% extends 'base.html' %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

    <div class="container lg:w-5/12 md:w-2/3 mx-auto my-10 flex flex-col items-center p-6 shadow w-full">
        {% include 'partials/social_login.html' %}
        {% include 'mixins/auth/auth_form.html' with form=form cta="Log In" %}

        <div class="mt-5">
            <span>Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-green-800 font-medium">Sign up</a>
        </div>
    </div>
{% endblock content %}
    
    

templates/users/signup.html
{% extends 'base.html' %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

    <div class="container lg:w-5/12 md:w-2/3 mx-auto my-10 flex flex-col items-center p-6 shadow w-full">
    {% include 'partials/social_login.html' %}
    {% include 'mixins/auth/auth_form.html' with form=form cta="Sign Up" %}

    <div class="mt-5">
        <span>Already have an account?</span>
        <a href="{% url 'users:login' %}" class="text-green-800 font-medium">Log In</a>
    </div>
    </div>
{% endblock content %}
    
    

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

    <div class="container lg:w-5/12 md:w-2/3 mx-auto my-10 flex flex-col items-center p-6 shadow w-full">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Password" %}
    </div>
{% endblock content %}
    
    

templates/users/update-profile.html
{% extends 'base.html' %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}

    <div class="container lg:w-5/12 md:w-2/3 mx-auto my-10 flex flex-col items-center shadow p-6 w-full">
        {% include 'mixins/auth/auth_form.html' with form=form cta="Update Profile" %}

    {% if object.login_method == "email" %}
        <div class="mt-5">
            <a href="{%url "users:password" %}" class="text-green-800 font-medium">Wanna change password?</a>
        </div>
    {% endif %}
    </div>
{% endblock content %}
    
    

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block content %}

    <div class="container lg:w-5/12 md:w-2/3 mx-auto my-10 flex flex-col items-center shadow p-6  w-full">
        {% include 'mixins/user_avatar.html' with user=user_obj %}
            
        <span class="text-3xl mt-2">
            {{user_obj.first_name}} {{user_obj.last_name}}
            {% if user_obj.superhost %}
                <i class="fas fa-check-circle text-blue-300 text-lg"></i>
            {% endif %}
                
        </span>
        <span class="text-lg mt-2">{{user_obj.bio}}</span>

        {% if user == user_obj %}
        <a href="{% url "users:update" %}" class="btn_link mt-5">Edit Profile</a>
        <a href="{% url "reservations:lists" %}" class="btn_link mt-5">See My Reservations</a>
        <a href="{% url "users:conversation" %}" class="btn_link mt-5">See My Conversations</a>
        {% endif %}
    </div>

    {% if user_obj.rooms.all %}
    <div class="container lg:w-3/4 md:w-10/12 sm:w-full mx-auto my-10 flex flex-col items-center">
        <div class="mb-12 text-2xl font-medium">
            {{user_obj.first_name}}'s Room
        </div>
        <div class="flex flex-wrap -mx-40 mb-10 w-full">
            {% for room in user_obj.rooms.all %}
                {% include 'mixins/rooms/room_card.html' with room=room %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock content %}
    
    